services:
  mongodb:
    image: 'mongo:latest'
    hostname: mongo
    container_name: analytics_db
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '58000:27017'
    networks:
      - kfk-net

networks:
  kfk-net:
    external: true