services:
  postgres:
    image: 'postgres:latest'
    hostname: postgres
    container_name: crm_db
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pgoutput"
      - "-c"
      - "wal_level=logical"
    networks:
      - kfk-net

networks:
  kfk-net:
    external: true