server:
  port: 8083
spring:
  application:
    name: document_store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres_db:5432/mydatabase
    username: myuser
    password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/crm
