server:
  port: 8084
spring:
  application:
    name: analytics
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/mydatabase
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/crm
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest