server:
  port: 8082
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      mvc:
        http-client:
          type: autodetect
        routes:
          - id: crm
            uri: http://localhost:8080
            predicates:
              - Path=/crm/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: communication-manager
            uri: http://localhost:8081
            predicates:
              - Path=/communication-manager/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: document-store
            uri: http://localhost:8083
            predicates:
              - Path=/document-store/**
            filters:
              - StripPrefix=1
              - TokenRelay
          - id: ui
            uri: http://localhost:5173
            predicates:
              - Path=/ui/**
          - id: home
            uri: http://localhost:8082
            predicates:
              - Path=/
            filters:
              - RedirectTo=301, http://localhost:8082/ui

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/crm
        registration:
          apigateway:
            provider: keycloak
            client-id: apigateway
            client-secret: IRENkPNCvWzPe1fjHrmF1jkzR10Vxr1j
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/apigateway
