server:
  port: 8080
spring:
  application:
    name: crm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://postgres_db:5432/mydatabase
    username: myuser
    password: secret
  #sql:
  #  init:
  #    mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/crm
